packages:
  - test-species
  - saccharomyces-cerevisiae
  - homo-sapiens
  - mus-musculus
  - rattus-norvegicus
  - danio-rerio
  - drosophila-melanogaster
  - arabidopsis-thaliana
  - caenorhabditis-elegans
  - gallus-gallus
  - bos-taurus
  - sus-scrofa
  - catalogue

catalog:
  'turbo': ^2.5.6
  '@changesets/cli': ^2.29.6
  '@platforma-sdk/package-builder': ^3.0.1
